// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjFRkYArQgHw4wpntPMMlQFUSm-px6deg',
    appId: '1:546625672710:web:1f06ac3e174637adfed587',
    messagingSenderId: '546625672710',
    projectId: 'qunnfooddeli',
    authDomain: 'qunnfooddeli.firebaseapp.com',
    storageBucket: 'qunnfooddeli.appspot.com',
    measurementId: 'G-QFREZBY80K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChkW_mhH81EsSEcYaGEpUbXnE_vgbHHtY',
    appId: '1:546625672710:android:4be9d94f7738b91dfed587',
    messagingSenderId: '546625672710',
    projectId: 'qunnfooddeli',
    storageBucket: 'qunnfooddeli.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALuaDWHKErWDDDgNn4goAkpFJL_5mJmDA',
    appId: '1:546625672710:ios:130b3a9f824190d5fed587',
    messagingSenderId: '546625672710',
    projectId: 'qunnfooddeli',
    storageBucket: 'qunnfooddeli.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALuaDWHKErWDDDgNn4goAkpFJL_5mJmDA',
    appId: '1:546625672710:ios:130b3a9f824190d5fed587',
    messagingSenderId: '546625672710',
    projectId: 'qunnfooddeli',
    storageBucket: 'qunnfooddeli.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjFRkYArQgHw4wpntPMMlQFUSm-px6deg',
    appId: '1:546625672710:web:7a0983e341b68036fed587',
    messagingSenderId: '546625672710',
    projectId: 'qunnfooddeli',
    authDomain: 'qunnfooddeli.firebaseapp.com',
    storageBucket: 'qunnfooddeli.appspot.com',
    measurementId: 'G-DLX7XH1QLT',
  );
}
